name: Deploy JSP on GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Application
      run: ./gradlew clean bootJar

    - name: Build Docker Image
      run: |
        docker build -t my-jsp-app .
        docker run -d -p 8080:8080 my-jsp-app

    - name: Expose Application
      run: echo "Your app is running on the GitHub Actions server"